"""Addition of column complete  new

Revision ID: 44f1e86c3259
Revises: 9b22d1e30ff1
Create Date: 2023-07-13 22:04:48.632083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f1e86c3259'
down_revision = '9b22d1e30ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_new', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('completed_new')

    # ### end Alembic commands ###
